#!/bin/bash
echo ""
echo "********************************************************************"
echo "*                                                                  *"
echo "* Note: Map a volume to this container to get your firmware out!   *"
echo "*                                                                  *"
echo "* docker run -it -v /tmp:/esp/esp-at/build/factory espat           *"
echo "*                                                                  *"
echo "* Configure new firmwware:                                         *"
echo "*                                                                  *"
echo "* cd /esp/esp-at && ./build.py menuconfig                          *"
echo "*                                                                  *"
echo "* Then with docker shell still open...                             *" 
echo "*                                                                  *"
echo "* Build:                                                           *"
echo "*                                                                  *"
echo "* cd /esp/esp-at && ./build.py build                               *"
echo "********************************************************************"
echo ""
/bin/bash
